---
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}

library("DiagrammeR") 
library("dplyr")

## code from https://daranzolin.github.io/2018-01-07-probability-trees/
## modified to be a shiny app by Israel A. Almodóvar-Rivera.
bayes_probability_tree <- function(prior,sensitivity, specificity) {
  
  if (!all(c(prior,sensitivity, specificity) > 0) && !all(c(prior,sensitivity, specificity) < 1)) {
    stop("probabilities must be greater than 0 and less than 1.",
         call. = FALSE)
  }
  c_prior <- 1 - prior
  c_tp <- 1 - sensitivity
  c_tn <- 1 - specificity
  

  b1 <- prior * sensitivity
  b2 <- prior * c_tp
  b3 <- c_prior * c_tn
  b4 <- c_prior * specificity
  
  bp <- round(b1/(b1 + b3),digits=4)
  
  labs <- round(c(prior, c_prior, sensitivity, c_tp, specificity, c_tn, b1, b2, b4, b3),digits=4)
  labs <- c("",labs)
  
  tree <-
    create_graph() %>%
    add_n_nodes(
      n = 11,
      type = "path",
      label = labs,
      node_aes = node_aes(
        shape = "circle",
        height = 1,
        width = 1,
        fontsize=15,
        fillcolor = "#E5F5E0",
        fontcolor="black",
        x = c(0, 3, 3, 6, 6, 6, 6, 8, 8, 8, 8),
        y = c(0, 2, -2, 3, 1, -3, -1, 3, 1, -3, -1))) %>% 
    add_edge(
      from = 1,
      to = 2,
      edge_aes = edge_aes(
        label = "Prior",
        fontsize=13,
      )
    ) %>% 
    add_edge(
      from = 1, 
      to = 3,
      edge_aes = edge_aes(
        label = "1-Prior",
        fontsize=13,
      )
    ) %>% 
    add_edge(
      from = 2,
      to = 4,
      edge_aes = edge_aes(
        label = "True Positive", ## Sensitivity=TRUE POSITIVE
        fontsize=13,
      )
    ) %>% 
    add_edge(
      from = 2,
      to = 5,
      edge_aes = edge_aes(
        label = "False Negative",
        fontsize=13,
      )
    ) %>% 
    add_edge(
      from = 3,
      to = 7,
      edge_aes = edge_aes(
        label = "False Positive",
      fontsize=13,
      )
    ) %>% 
    add_edge(
      from = 3,
      to = 6,
      edge_aes = edge_aes(
        label = "True Negative", ## Specificity = True Negative
        fontsize=13,
      )
    ) %>% 
    add_edge(
      from = 4,
      to = 8,
      edge_aes = edge_aes(
        label = "=",
        fontsize=13,
      )
    ) %>% 
    add_edge(
      from = 5,
      to = 9,
      edge_aes = edge_aes(
        label = "=",
        fontsize=13,
      )
    ) %>% 
    add_edge(
      from = 7,
      to = 11,
      edge_aes = edge_aes(
        label = "=",
        fontsize=13,
      )
    ) %>% 
    add_edge(
      from = 6,
      to = 10,
      edge_aes = edge_aes(
        label = "=",
        fontsize=13,
      )
    ) 
  tree
}

```

```{r probability-module-setup,echo=FALSE}
sidebarLayout(
  sidebarPanel(
    numericInput(inputId = "prior",label = "Prior Probability",value=0.05,min = 0,max = 1,step = 0.01),
    numericInput(inputId = "tp",label = "Sensitivity (True Positive)",value=0.95,min = 0,max = 1,step = 0.01),
    numericInput(inputId = "tn",label = "Specificity (True Negative)",value=0.9,min = 0,max = 1,step = 0.01),
submitButton("Submit"),
    ),
    mainPanel(
      tabPanel("Bayes Tree Diagram",
#               h4("Posterior Probability Tree"),
#               br(),
#      grVizOutput('diagram', width = "100%", height = "460px"),
      uiOutput('diagram', width = "500px", height = "500px"),
#      br(),
#      h4("Posterior Probability"),
uiOutput("posterior"),
      )
      )
    )

# output$diagram <- renderGrViz({
#    graph <- bayes_probability_tree(prior = input$prior, 
#                                    sensitivity = input$tp,
#                                    specificity = input$tn)
#     grViz({
# generate_dot(graph)
#     })
#     
# })


output$diagram <- renderUI({
   graph <- bayes_probability_tree(prior = input$prior, 
                                   sensitivity = input$tp,
                                   specificity = input$tn)
    print(render_graph(graph))
    
})
output$posterior <- renderUI({
  c_prior <- 1 - input$prior
  c_tp <- 1 - input$tp
  c_tn <- 1 - input$tn
  

  b1 <- input$prior * input$tp
  b2 <- input$prior * c_tp
  b3 <- c_prior * c_tn
  b4 <- c_prior * input$tn
  
  bp <- round(b1/(b1 + b3),digits=4)

    withMathJax(
      paste(paste0("The probability of having (prior = ", input$prior,")",
             " after testing positive,i.e., $$P(Disease|Testing \\: Positive) = "),
sprintf("\\frac{%.4f \\times %.4f}{%.4f \\times %.4f+%.4f \\times %.4f}= %.4f $$",input$tp,input$prior,input$tp,input$prior,c_prior,input$tn,bp))
      )
})

```
