---
title: "Data Upload/Input"
output: html_document
runtime: shiny
---

Welcome to FIRSTkit!We are happy (sort of) that you are here! 

```{r setup, include=FALSE,message=FALSE}
library("readODS")
library("readxl")
library("googlesheets4")
library("DT")
fExt <- function(filename) {
  nameSplit <- strsplit(x = filename, split = "\\.")[[1]]
  fnameext <- paste(".",nameSplit[length(nameSplit)],sep="")
  return(fnameext)
}

extract <- function(text) {
  text <- gsub(" ", "", text)
  split <- strsplit(text, ",", fixed = FALSE)[[1]]
  as.numeric(split)
}

read_data_FIRSTkit <- function(fname, input,choice="Upload File"){
    
    choice <- match.arg(arg = choice, 
                        choices = c("Upload File (Acceptable extensions)",
                                    "Google Sheets",
                                    "Input Data"))
    
    if(choice=="Upload File"){
    
    ##check extension
    ext <- fExt(input)#$file$datapath)
      
    if(!(ext %in% c(".csv",".txt",".xls",".xlsx",".dat",".ods"))){
      stop("Not supported extension")
    } else{
      if(ext %in% c(".xls",".xlsx")){
           df <- read_excel(fname,sheet=1)
      }      
     if(ext %in% c(".csv",".txt",".dat")){
       df <- read.table(fname,
                  header = input$header,
                  sep = input$sep,
                  quote = input$quote)
     }
      if(ext %in% c(".ods")){
        df <- read_ods(path = fname)
      }
    }
    }
    if(choice=="Google Sheets"){
        df <- read_sheet(fname)
    }
    if(choice=="Input Data"){
      x <- extract(fname)
      tt<- data.frame(x = x)
    } 
     
    df
}

```

```{r descriptive-stats, echo=FALSE,message=FALSE}
sidebarLayout(
  sidebarPanel(
    selectInput(
      inputId = "datachoice",
      label = "Input/Upload",
      choices = c("Upload File","Google Sheets","Input Data"),
      multiple = FALSE,
      selected = "Upload File"),
    hr(),
    conditionalPanel(
    condition = "input.datachoice == 'Input Data'",
    textInput("x", "Data", value = "",
    placeholder = "Enter data values separated by a comma, e.g. 1.2, 3.14, 3.1417, etc."),
    hr(),
    ),
    conditionalPanel(
    condition = "input.datachoice == 'Upload File'",
    fileInput("file1", "Choose File",
              multiple = FALSE,
              accept = c("text/csv",                       "text/comma-separated-values,text/plain",
                         ".csv",".txt",".xlsx",".xls")),
    hr(),
    ## Input: Checkbox if file has header ----
    checkboxInput("header", "Header", TRUE),
    ## Input: Select separator ----
    radioButtons("sep", "Separator",
                  choices = c(Comma = ",",
                              Semicolon = ";",
                              Tab = "\t",
                              WhiteSpace=""),
                selected = ","),
        
    ### Input: Select quotes ----
    radioButtons("quote", "Quote",
                 choices = c(None = "",
                            "Double Quote" = '"',
                            "Single Quote" = "'"),
                selected = '"'),
    submitButton("Submit")
    ),
    conditionalPanel(
    condition = "input.datachoice == 'Google Sheets'",
    textInput("gsheets", "URL/Key", value = "", placeholder = "Enter URL or Key"),
    submitButton("Submit"),
    helpText("FIRSTkit uses the R package googlesheets4. For any question about googlesheets4 package, see https://github.com/tidyverse/googlesheets4.")
    )
    ),
    mainPanel(
      tabsetPanel(type = "tabs",
      tabPanel("Data", 
      dataTableOutput('tbl1'),
      icon=icon("table"))
      )
      )
    )


d <- reactive({  

  tt <- read_data_FIRSTkit(fname=input$file$datapath,input)
  var.opts<-colnames(tt)
  updateSelectInput(inputId =  "variable", choices = var.opts)
  updateSelectInput(inputId = "group", choices = var.opts)

  return(tt)
})

output$tbl1 <- renderDataTable({
    d()
  })

```
