---
title: First Impressions R-based Statistics Toolkit (FIRSTkit)
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library("shiny")
library("ggplot2")
library("plotly")
library("rmarkdown")
library("knitr")
library("pander")
library("shinythemes")
knitr::opts_chunk$set(echo = TRUE)
```

### Home 

Welcome to **FIRSTkit** a modern web-based software system for introductory statistical analysis.

```{r inputs-one-sample, echo=FALSE}


  sidebarPanel(
    selectInput(
      inputId = "datachoice",
      label = "Data (Input some data or upload a file)",
      choices = c("Input data","Upload file","Upload .xls/.xslx file"),
      multiple = FALSE,
      selected = NULL##"Input data"
    ),
    hr(),
    conditionalPanel(
    condition = "input.datachoice == 'Input data'",
    textInput("x", "Data", value = "",
    placeholder = "Enter values separated by a comma with decimals as points, e.g. 1.2, 3.14, 3.1417, etc."),
    hr(),
    ),
    conditionalPanel(
    condition = "input.datachoice == 'Upload file'",
    fileInput("file1", "Choose CSV File",
              multiple = TRUE,
              accept = c("text/csv",
                         "text/comma-separated-values,text/plain",
                         ".csv")),
    hr(),
        # Input: Checkbox if file has header ----
    checkboxInput("header", "Header", TRUE),
        
    # Input: Select separator ----
    radioButtons("sep", "Separator",
                  choices = c(Comma = ",",
                              Semicolon = ";",
                              Tab = "\t"),
                  selected = ","),
        
        # Input: Select quotes ----
    radioButtons("quote", "Quote",
                 choices = c(None = "",
                            "Double Quote" = '"',
                            "Single Quote" = "'"),
                selected = '"'),
    ),
    conditionalPanel(
    condition = "input.datachoice == 'Upload .xls/.xslx file'",
    fileInput('file2', 'Choose .xls/.xlsx file',accept = c(".xlsx",".xls"))
      ),

    )
  
    


```




If you have any question or want to report something.  Send a message to *israel.almodovar@upr.edu* or *maitra@iastate.edu*.
