---
title: "Probability Theory"
output: html_document
runtime: shiny
---


```{r setup, include=FALSE}

library("gridExtra")
library("knitr")
library("pander")
library("DiagrammeR") 
library("eulerr")
library("ggVennDiagram")
library("ggplot2")
knitr::opts_chunk$set(echo = TRUE)
 extract <- function(text) {
    text <- gsub(" ", "", text)
    split <- strsplit(text, ",", fixed = FALSE)[[1]]
    as.numeric(split)
 }

x <- list(A=1:5,B=2:7,C=3:6,D=4:9,E=0:10,FF = 0:5)
## perform diagram
bayes_probability_tree <- function(prior, true_positive, true_negative) {
  
  if (!all(c(prior, true_positive, true_negative) > 0) && !all(c(prior, true_positive, true_negative) < 1)) {
    stop("probabilities must be greater than 0 and less than 1.",
         call. = FALSE)
  }
  c_prior <- 1 - prior
  c_tp <- 1 - true_positive
  c_tn <- 1 - true_negative
  
  ##round4 <- purrr::partial(round, digits = 4)
  
  ##b1 <- round4(prior * true_positive)
  ##b2 <- round4(prior * c_tp)
  ##b3 <- round4(c_prior * c_tn)
  ##b4 <- round4(c_prior * true_negative)
  b1 <- prior * true_positive
  b2 <- prior * c_tp
  b3 <- c_prior * c_tn
  b4 <- c_prior*true_negative
  bp <- b1/(b1+b3)
  ##bp <-  round4(b1/(b1 + b3))
  
  labs <- c("X", prior, c_prior, true_positive, c_tp, true_negative, c_tn, b1, b2, b4, b3)
  
  tree <-
    create_graph() %>%
    add_n_nodes(
      n = 11,
      type = "path",
      label = labs,
      node_aes = node_aes(
        shape = "circle",
        height = 1,
        width = 1,
        x = c(0, 3, 3, 6, 6, 6, 6, 8, 8, 8, 8),
        y = c(0, 2, -2, 3, 1, -3, -1, 3, 1, -3, -1))) %>% 
    add_edge(
      from = 1,
      to = 2,
      edge_aes = edge_aes(
        label = "Prior"
      )
    ) %>% 
    add_edge(
      from = 1, 
      to = 3,
      edge_aes = edge_aes(
        label = "Complimentary Prior"
      )
    ) %>% 
    add_edge(
      from = 2,
      to = 4,
      edge_aes = edge_aes(
        label = "True Positive"
      )
    ) %>% 
    add_edge(
      from = 2,
      to = 5,
      edge_aes = edge_aes(
        label = "False Negative"
      )
    ) %>% 
    add_edge(
      from = 3,
      to = 7,
      edge_aes = edge_aes(
        label = "False Positive"
      )
    ) %>% 
    add_edge(
      from = 3,
      to = 6,
      edge_aes = edge_aes(
        label = "True Negative"
      )
    ) %>% 
    add_edge(
      from = 4,
      to = 8,
      edge_aes = edge_aes(
        label = "="
      )
    ) %>% 
    add_edge(
      from = 5,
      to = 9,
      edge_aes = edge_aes(
        label = "="
      )
    ) %>% 
    add_edge(
      from = 7,
      to = 11,
      edge_aes = edge_aes(
        label = "="
      )
    ) %>% 
    add_edge(
      from = 6,
      to = 10,
      edge_aes = edge_aes(
        label = "="
      )
    ) 
  message(glue::glue("The probability of having (prior) after testing positive is {bp}"))
  render_graph(tree)
  invisible(tree)

}

# ggVennDiagram(x)  # 4d venn
# ggVennDiagram(x[1:3])  # 3d venn
# ggVennDiagram(x[1:2],label = "percent",
#               label_percent_digit = 2,edge_size = 0.5)+
#   theme(legend.position="none")+
#   scale_fill_distiller(palette = "Dark2")+
#   scale_alpha(range=seq(0.1,0.5,length.out=2))


```

```{r probability-module-setup,echo=FALSE}
sidebarLayout(
  sidebarPanel(
    selectInput(
      inputId = "probabilitychoice",
      label = "Chose event",
      choices = c("Probability Events","Bayes Tree Diagram"),
      multiple = FALSE,
      selected = NULL),
    hr(),
    conditionalPanel(
    condition = "input.probabilitychoice == 'Probability Events'",
    textInput("x", "Data", value = "",
    placeholder = "Enter values separated by a comma with decimals as points, e.g. 1.2, 3.14, 3.1417, etc."),
    hr(),
    ),
    conditionalPanel(
    condition = "input.probabilitychoice == 'Bayes Tree Diagram'",
textInput("prior","Prior Probability",value="0.07",placeholder="Indicate the value of the Prior"),
textInput("tp","True Positive",value="0.95",placeholder="Input the value for the true positive"),
textInput("tn","True Negative",value="0.98",placeholder="Input the value for the true negative"),
submitButton("Submit"),
    hr(),
    ),
    ),
    mainPanel(
      tabsetPanel(type = "tabs",
      tabPanel("Venn Diagram", 
      uiOutput("vennoutput")),
      tabPanel("Bayes Tree Diagram",
      grVizOutput("diagram"))
      )
      )
    )

output$treeoutput <- renderDiagrammeR({
  prior <- as.numeric(input$prior)
  TP <- as.numeric(input$tp)
  TN <- as.numeric(input$tn)
  bayes_probability_tree(prior = prior, true_positive = TP, true_negative = TN)
})

 output$diagram <- renderGrViz({
           prior <- as.numeric(input$prior)
  TP <- as.numeric(input$tp)
  TN <- as.numeric(input$tn)
  bb <- bayes_probability_tree(prior = prior, true_positive = TP, true_negative = TN)

    grViz({
      bb$dot_code
    })
  })

```

If you have any question or want to report something. Submit a message at github.com
