---
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library("car")
library("readxl")
knitr::opts_chunk$set(echo = TRUE)
  extract <- function(text) {
    text <- gsub(" ", "", text)
    split <- strsplit(text, ",", fixed = FALSE)[[1]]
    as.numeric(split)
  }
  
loc.test <- function(df,v1,groups){
  x <-df[,v1]
  g <- df[,groups]
  kk <- kruskal.test(x = x,g = g)
  KW.summary <- cbind("Statistic"= kk$statistic,
    "DF" = kk$parameter,
    "p-value" = kk$p.value)
  rownames(KW.summary) <- kk$method

  fit.lm <- lm(x ~ g,data=df)
anova(fit)
  
}  
  
```




```{r inputs, echo=FALSE}
sidebarLayout(
  sidebarPanel(
    selectInput(
      inputId = "datachoice",
      label = "Data",
      choices = c("Upload file","Upload .xls/.xslx file"),
      multiple = FALSE,
      selected = NULL
    ),
    hr(),
    conditionalPanel(
    condition = "input.datachoice == 'Upload file'",
    fileInput("file1", "Choose File",
              multiple = TRUE,
              accept = c("text/csv",
                         "text/comma-separated-values,text/plain",
                         ".csv",".xslx",".xls")),
    hr(),
        # Input: Checkbox if file has header ----
    checkboxInput("header", "Header", TRUE),
        
    # Input: Select separator ----
    radioButtons("sep", "Separator",
                  choices = c(Comma = ",",
                              Semicolon = ";",
                              Tab = "\t"),
                  selected = ","),
        
        # Input: Select quotes ----
    radioButtons("quote", "Quote",
                 choices = c(None = "",
                            "Double Quote" = '"',
                            "Single Quote" = "'"),
                selected = '"'),
    ),
    conditionalPanel(
    condition = "input.datachoice == 'Upload .xls/.xslx file'",
    fileInput('file2', 'Choose .xls/.xlsx file',accept = c(".xlsx",".xls"))
    
    ),
    selectInput('type', 'Sums of Squares Type',
                    c(I = 'type1', II = 'type2', III = 'type3'), 'type1'),
 ##   textInput("mu0","\\(  H_0:\\mu_1=\\mu_2 = \\cdots = \\mu_k \\)",value="0",placeholder="Indicate the true value for the difference of location of interest"),
##        textInput("sigma0","\\(  H_0:\\sigma_1=\\sigma_2 = \\cdots = \\sigma_k \\)",value="0",placeholder="Indicate the true value for the difference of dispersion of interest"),
    uiOutput('var'),
    ),
      mainPanel(
        tabsetPanel(type = "tabs",
#        tabPanel("Groups Summaries",
#        tableOutput("GroupsDescription")),
        tabPanel("Location Inference",
withMathJax(),
        h4('Analysis of Variance Table'),
        tableOutput('aovSummary'),
withMathJax(),
        h4('Kruskal-Wallis Rank Sum Test'),
        tableOutput('KWSummary')),
        tabPanel("Dispersion Inference",
        h4("Bartlett test for homogeneity of variances"),
        uiOutput("BartlettSummary"),
        h4("Fligner-Killeen test for homogeneity of variances"),
        uiOutput("FlignerSummary"))
        )
  )
)
    
d <- reactive({  
  if(!is.null(input$file1)){
    req(input$file1)
    
    tt <- read.csv(input$file1$datapath,
                   header = input$header,
                   sep = input$sep,
                   quote = input$quote)
   
  } 
  if(!is.null(input$file2)){
    req(input$file2)
    tt <- as.data.frame(read_excel(input$file2$datapath,sheet=1))
  }
  if(is.null(input$file1) & is.null(input$file2)){
  x <- extract(input$x)
  tt<- data.frame(x = x)
  } 
  
  var.opts <- colnames(tt)
  updateSelectInput(inputId =  "variable1", choices = var.opts)
  updateSelectInput(inputId =  "variable2", choices = var.opts)
  return(tt)
})

output$var <- renderUI({
list(selectInput("dvar", "Response (y)", choices = names(d()),selected = NULL),
selectInput("ivar", "Fixed-effects ", choices = names(d()),selected = NULL)#,
#                actionButton("submit", "Submit")
)
})

# output$GroupsDescription <- renderTable({
#   d2 <- d()
#   xbars <- with(data=d2,tapply(input$dvar,input$ivar,mean,na.rm=TRUE))
#   sds <- with(data=d2,tapply(input$dvar,input$ivar,sd,na.rm=TRUE))
#   nks <- with(data=d2,table(input$ivar))
#   
#   dpt <- cbind(nks,xbars,sds)
#   colnames(dpt) <- c("\\( n \\)","\\( \\bar{x} \\)", "\\( s \\)")
#   dpt
# },rownames=TRUE,colnames=TRUE)

output$aovSummary <- renderTable({
#        if(input$submit > 0){
if(input$type == 'type1'){
return(isolate(anova(lm(as.formula(paste(input$dvar,"~",input$ivar,collapse="")), data =d()))))
}
if(input$type == 'type2'){
return(isolate(Anova(lm(as.formula(paste(input$dvar,"~",input$ivar,collapse="")), data =d()), Type = "II", test.statistic = "F")))
}
if(input$type == 'type3'){
isolate(
fit <- aov(lm(as.formula(paste(input$dvar,"~",input$ivar,collapse="")), data =d()))
)
return(drop1(fit, ~ . , test = 'F'))
#      }
}
},rownames=TRUE)
      
output$KWSummary <- renderTable({

          fit <- kruskal.test(as.formula(paste(input$dvar,"~",input$ivar,collapse="")), data =d())
          if(fit$p.value >= 0.001){
          XX <- cbind(fit$parameter, fit$statistic, fit$p.value)
          } else{
            XX <- data.frame(fit$parameter,
                             fit$statistic,
                             "<0.001")
          }
          colnames(XX) <- c("$$ DF $$","$$ X^2-$$ statistic","$$ \\mathbb{P}(>X^2)$$")
          rownames(XX) <- "Kruskal-Wallis"
          XX
#
      },rownames = TRUE,colnames = TRUE)

output$BartlettSummary <- renderTable({
  #      if(input$submit > 0){
        
          fit <- bartlett.test(as.formula(paste(input$dvar,"~",input$ivar,collapse="")), data =d())
          if(fit$p.value >= 0.001){
          XX <- cbind(fit$parameter, fit$statistic, fit$p.value)
          } else{
            XX <- data.frame(fit$parameter,
                             fit$statistic,
                             "<0.001")
          }
          colnames(XX) <- c("$$ DF $$","$$ X^2-$$ statistic","$$ \\mathbb{P}(>X^2)$$")
          rownames(XX) <- "Bartlett"
          XX
  #      }
      },rownames = TRUE,colnames = TRUE)

output$FlignerSummary <- renderTable({
  #      if(input$submit > 0){
        
          fit <- fligner.test(as.formula(paste(input$dvar,"~",input$ivar,collapse="")), data =d())
          if(fit$p.value >= 0.001){
          XX <- cbind(fit$parameter, fit$statistic, fit$p.value)
          } else{
            XX <- data.frame(fit$parameter,
                             fit$statistic,
                             "<0.001")
          }
          colnames(XX) <- c("$$ DF $$","$$ X^2-$$ statistic","$$ \\mathbb{P}(>X^2)$$")
          rownames(XX) <- "Fligner-Killeen"
          XX
  #      }
      },rownames = TRUE,colnames = TRUE)


```

