---
title: "Two-Sample Inference"
output: html_document
runtime: shiny
---


```{r setup, include=FALSE}
library("readxl")
knitr::opts_chunk$set(echo = TRUE)
  extract <- function(text) {
    text <- gsub(" ", "", text)
    split <- strsplit(text, ",", fixed = FALSE)[[1]]
    as.numeric(split)
  }

all.t.two.sample.test <- function(x, y, delta0 = 0,alpha = 0.05,...){
  twosided <- t.test(x = x, y = y,mu = delta0, 
                     alternative = "two.sided",
                     conf.level = 1-alpha)
  oneless <- t.test(x = x, y = y,mu = delta0, 
                    alternative = "less",
                    conf.level = 1-alpha)
  onegreater <- t.test(x = x, y = y,mu = delta0, 
                       alternative = "greater",
                       conf.level = 1-alpha)
  
  tt <- round(c(twosided$statistic, oneless$statistic, onegreater$statistic),digits=3)
  pval <- round(c(twosided$p.value, oneless$p.value, onegreater$p.value),digits = 3) 
  
  ci <- c(paste("(",paste(round(twosided$conf.int[1],digits=3),",",
                          round(twosided$conf.int[2],digits=3),sep=""),")",sep=""),
          paste("(",paste(round(oneless$conf.int[1],digits=3),",",
                          round(oneless$conf.int[2],digits=3),sep=""),")",sep=""),
          paste("(",paste(round(onegreater$conf.int[1],digits=3),",",
                          round(onegreater$conf.int[2],digits=3),sep=""),")",sep=""))
  
  res <- data.frame(Test = tt,Pval = pval, CI =ci)
  names(res) <- c("statistic","p-value",paste(as.character((1-alpha)*100),"% CI",sep=""))
  
#   rownames(res) <- c(paste("\\(H_{1}: \\mu_{1}-\\mu_{2} =\\) ",delta0,sep=""),
#                      paste("H_1: mu_1-mu_2 < ",delta0,sep=""),
#                      paste("H_1: mu_1-mu_2 > ",delta0,sep=""))
# res
  rownames(res) <- c(paste("\\(H_{1}: \\mu_{1}-\\mu_{2} \\neq \\) ",delta0,sep=""),
                     paste("\\(H_{1}: \\mu_{1}-\\mu_{2} <\\) ",delta0,sep=""),
                     paste("\\(H_{1}: \\mu_{1}-\\mu_{2} >\\) ",delta0,sep=""))
res

}

##
all.wilcoxon.two.sample.test <- function(x,  y, delta0 = 0, alpha = 0.05,...){
  twosided <- wilcox.test(x = x, y= y, mu = delta0, 
                          alternative = "two.sided",
                          conf.level = 1-alpha,conf.int = TRUE)
  oneless <- wilcox.test(x = x, y = y,mu = delta0, 
                         alternative = "less",
                         conf.level = 1-alpha,conf.int = TRUE)
  onegreater <- wilcox.test(x = x, y= y, mu = delta0, 
                            alternative = "greater",
                            conf.level = 1-alpha,conf.int = TRUE)
  
  tt <- round(c(twosided$statistic, oneless$statistic, onegreater$statistic),digits=3)
  pval <- round(c(twosided$p.value, oneless$p.value, onegreater$p.value),digits = 3) 
  
  ci <- c(paste("(",paste(round(twosided$conf.int[1],digits=3),",",
                          round(twosided$conf.int[2],digits=3),sep=""),")",sep=""),
          paste("(",paste(round(oneless$conf.int[1],digits=3),",",
                          round(oneless$conf.int[2],digits=3),sep=""),")",sep=""),
          paste("(",paste(round(onegreater$conf.int[1],digits=3),",",
                          round(onegreater$conf.int[2],digits=3),sep=""),")",sep=""))
  
  res <- data.frame(Test = tt,Pval = pval, CI =ci)
  names(res) <- c("statistic","p-value",paste(as.character((1-alpha)*100),"% CI",sep=""))
  
 rownames(res) <- c(paste("\\(H_{1}: \\mu_{1}-\\mu_{2} \\neq \\) ",delta0,sep=""),
                     paste("\\(H_{1}: \\mu_{1}-\\mu_{2} <\\) ",delta0,sep=""),
                     paste("\\(H_{1}: \\mu_{1}-\\mu_{2} >\\) ",delta0,sep=""))
res
}

all.var.two.sample.test <- function(x, y, ratio = 1,alpha = 0.05,...){
  twosided <- var.test(x = x, y = y,ratio=ratio, 
                     alternative = "two.sided",
                     conf.level = 1-alpha)
  oneless <- var.test(x = x, y = y,ratio=ratio, 
                     alternative = "less",
                     conf.level = 1-alpha)
  onegreater <- var.test(x = x, y = y,ratio=ratio, 
                     alternative = "greater",
                     conf.level = 1-alpha)
  
  tt <- round(c(twosided$statistic, oneless$statistic, onegreater$statistic),digits=3)
  pval <- round(c(twosided$p.value, oneless$p.value, onegreater$p.value),digits = 3) 
  
  ci <- c(paste("(",paste(round(twosided$conf.int[1],digits=3),",",
                          round(twosided$conf.int[2],digits=3),sep=""),")",sep=""),
          paste("(",paste(round(oneless$conf.int[1],digits=3),",",
                          round(oneless$conf.int[2],digits=3),sep=""),")",sep=""),
          paste("(",paste(round(onegreater$conf.int[1],digits=3),",",
                          round(onegreater$conf.int[2],digits=3),sep=""),")",sep=""))
  
  res <- data.frame(Test = tt,Pval = pval, CI =ci)
  names(res) <- c("statistic","p-value",paste(as.character((1-alpha)*100),"% CI",sep=""))
  
  # rownames(res) <- c(paste("H_1: sigma^2_1/sigma^2_2 = ",ratio,sep=""),
  #                    paste("H_1: sigma^2_1/sigma^2_2 < ",ratio,sep=""),
  #                    paste("H_1: sigma^2_1/sigma^2_2 > ",ratio,sep=""))
  # res
  
   rownames(res) <- c(paste("\\(H_{1}: \\sigma^{2}_{1}/\\sigma^{2}_{2} \\neq \\)",ratio,sep=""),
                     paste("\\(H_{1}: \\sigma^{2}_{1}/\\sigma^{2}_{2} <\\)",ratio,sep=""),
                     paste("\\(H_{1}: \\sigma^{2}_{1}/\\sigma^{2}_{2} >\\)",ratio,sep=""))
res

}

all.ansari.two.sample.test <- function(x, y, ratio = 1,alpha = 0.05,...){
  twosided <- ansari.test(x = x, y = y, conf.int=TRUE, 
                     alternative = "two.sided",
                     conf.level = 1-alpha)
  oneless <- ansari.test(x = x, y = y,conf.int=TRUE,
                     alternative = "less",
                     conf.level = 1-alpha)
  onegreater <- ansari.test(x = x, y = y,conf.int=TRUE,
                     alternative = "greater",
                     conf.level = 1-alpha)
  
  tt <- round(c(twosided$statistic, oneless$statistic, onegreater$statistic),digits=3)
  pval <- round(c(twosided$p.value, oneless$p.value, onegreater$p.value),digits = 3) 
  
  ci <- c(paste("(",paste(round(twosided$conf.int[1],digits=3),",",
                          round(twosided$conf.int[2],digits=3),sep=""),")",sep=""),
          paste("(",paste(round(oneless$conf.int[1],digits=3),",",
                          round(oneless$conf.int[2],digits=3),sep=""),")",sep=""),
          paste("(",paste(round(onegreater$conf.int[1],digits=3),",",
                          round(onegreater$conf.int[2],digits=3),sep=""),")",sep=""))
  
  res <- data.frame(Test = tt,Pval = pval, CI =ci)
  names(res) <- c("statistic","p-value",paste(as.character((1-alpha)*100),"% CI",sep=""))
  
  # rownames(res) <- c(paste("H_1: sigma^2_1/sigma^2_2 = ",ratio,sep=""),
  #                    paste("H_1: sigma^2_1/sigma^2_2 < ",ratio,sep=""),
  #                    paste("H_1: sigma^2_1/sigma^2_2 > ",ratio,sep=""))
  # res
  
   rownames(res) <- c(paste("\\(H_{1}: \\sigma_{1}/\\sigma_{2} \\neq \\)",1,sep=""),
                     paste("\\(H_{1}: \\sigma_{1}/\\sigma_{2} <\\)",1,sep=""),
                     paste("\\(H_{1}: \\sigma_{1}/\\sigma_{2} >\\)",1,sep=""))
res

}

```

User can also select non-parametric approach. Wilcoxon-signed rank test uses the argument of $\mu_0$, although, this does not represent the mean but rather a location parameter. 

```{r inputs-two-sample, echo=FALSE}
sidebarLayout(
  sidebarPanel(
    selectInput(
      inputId = "datachoice",
      label = "Data (Input some data or upload a file)",
      choices = c("Upload file","Upload .xls/.xslx file","Input data"),
      multiple = FALSE,
      selected = NULL
    ),
    hr(),
    conditionalPanel(
    condition = "input.datachoice == 'Input data'",
    textInput("x", "Sample 1", value = "",
    placeholder = "Enter values separated by a comma with decimals as points, e.g. 1.2, 3.14, 3.1417, etc."),
        textInput("y", "Sample 2", value = "",
    placeholder = "Enter values separated by a comma with decimals as points, e.g. 0.5, 1, 2.7117, etc."),
    hr(),
    ),
    conditionalPanel(
    condition = "input.datachoice == 'Upload file'",
    fileInput("file1", "Choose File",
              multiple = TRUE,
              accept = c("text/csv",
                         "text/comma-separated-values,text/plain",
                         ".csv",".xslx",".xls")),
    hr(),
        # Input: Checkbox if file has header ----
    checkboxInput("header", "Header", TRUE),
        
    # Input: Select separator ----
    radioButtons("sep", "Separator",
                  choices = c(Comma = ",",
                              Semicolon = ";",
                              Tab = "\t"),
                  selected = ","),
        
        # Input: Select quotes ----
    radioButtons("quote", "Quote",
                 choices = c(None = "",
                            "Double Quote" = '"',
                            "Single Quote" = "'"),
                selected = '"'),
    ),
    conditionalPanel(
    condition = "input.datachoice == 'Upload .xls/.xslx file'",
    fileInput('file2', 'Choose .xls/.xlsx file',accept = c(".xlsx",".xls"))
    ),
    
    selectInput("variable1","Sample 1", choices = NULL),
    selectInput("variable2","Sample 2", choices = NULL),
    uiOutput("alpha_line"),
    textInput("delta0","\\(  H_0:\\mu_1-\\mu_2 = \\delta_0 \\)",value="0",placeholder="Indicate the true value for the difference of location of interest"),
     textInput("sigma0","\\( H_0:\\sigma^2_1/\\sigma^2_2 = R \\)",value="1",placeholder="Indicate the true value for the rat"),
    textInput("p0","\\( H_0: p_1 - p_2 = p_0 \\)",value="0.5",placeholder="Indicate the true value for the proportion of interest"),
        numericInput("nprop1", " Sample size (\\(n_1 \\))",
                     value = 50, min = 0, step = 1),
            numericInput("nprop2", " Sample size (\\(n_2 \\))",
                     value = 50, min = 0, step = 1),
        hr(),
        radioButtons(
          inputId = "propsuccess1",
          label = NULL,
          choices = c(
            "Proportion of success \\(\\hat{p}_1\\)" = "pr1",
            "Number of successes \\(x_1\\)" = "success1")),
       conditionalPanel(
          condition = "input.propsuccess == 'pr1'",
          numericInput("p_prop1", "Proportion of success (\\(\\hat{p}_1 \\))",value = 0.5, min = 0, max = 1, step = 0.001)),
        conditionalPanel(
          condition = "input.propsuccess == 'success1'",
          numericInput("x_prop1", "Number of successes(\\(x_1\\))",value = 20, min = 0, step = 1)),
    
        radioButtons(
          inputId = "propsuccess2",
          label = NULL,
          choices = c(
            "Proportion of success \\(\\hat{p}_2\\)" = "pr2",
            "Number of successes \\(x_2\\)" = "success2")),
       conditionalPanel(
          condition = "input.propsuccess == 'pr2'",
          numericInput("p_prop2", "Proportion of success (\\(\\hat{p}_2 \\))",value = 0.5, min = 0, max = 1, step = 0.001)),
        conditionalPanel(
          condition = "input.propsuccess == 'success2'",
          numericInput("x_prop2", "Number of successes(\\(x_2\\))",
                       value = 20, min = 0, step = 1
          )
        ),
        sliderInput("alpha","Significance level \\(\\alpha \\)",
                    min = 0,
                    max = 1,
                    value = 0.05,step=0.001),

    ),
      mainPanel(
        withMathJax(),
        tabsetPanel(type = "tabs",
        tabPanel("Location Inference",
        br(),
        tags$b("Two-Sample \\( t \\) test"),
        withMathJax(),
        uiOutput("tableUImean"),
        br(),
        tags$b("Mann-Whitney-Wilcoxon-signed rank test"),
        uiOutput("tableUIloc")),
        tabPanel("Dispersion Inference",
        br(),
        tags$b("Two-Sample Variance test"),
        withMathJax(uiOutput("tableUIvar")),
          br(),
        tags$b("Ansari-Bradley test"),
        withMathJax(uiOutput("tableUIansari")),
        ),
        tabPanel("Proportion Inference",
        tags$b("Two-Sample Proportion test"),
                 uiOutput("proportion"))
        )
  )
    )

d <- reactive({  
  if(!is.null(input$file1)){
    req(input$file1)
    
    tt <- read.csv(input$file1$datapath,
                   header = input$header,
                   sep = input$sep,
                   quote = input$quote)
   
  } 
  if(!is.null(input$file2)){
    req(input$file2)
    tt <- as.data.frame(read_excel(input$file2$datapath,sheet=1))
  }
  if(is.null(input$file1) & is.null(input$file2)){
  x <- extract(input$x)
  tt<- data.frame(x = x)
  } 
  
  var.opts <- colnames(tt)
  updateSelectInput(inputId =  "variable1", choices = var.opts)
  updateSelectInput(inputId =  "variable2", choices = var.opts)
  return(tt)
})

output$mean <- renderTable({
    delta0 <- as.numeric(input$delta0)
    alpha <- as.numeric(input$alpha)
    df <- d()
    
    x <- df[,input$variable1]
    y <- df[,input$variable2]
   all.t.two.sample.test(x = x, y = y, delta0 = delta0,alpha = alpha)

# ##d <-read.csv(file="../Data/palmer-penguins.csv",header=T)
# ##if(select.groups){
#      var.opts <- colnames(df)
# 
#   updateSelectInput(inputId =  "variableGroups", choices = var.opts)
#   groups <- unique(input$variableGroups)
#   updateSelectInput(inputId =  "variableG1", choices = groups)
#   updateSelectInput(inputId =  "variableG2", choices = groups)
#   x <- subset(x = d, input$variableGroups==variableG1,select=input$variable1)
#   y <- subset(x = d, input$variableGroups==variableG2,select=input$variable2)
#   ##    x <- df[df$groups ==input$variableG1,input$variable1]
#   ##    y <- df[df$groups ==input$variableG1,input$variable1]
# ##}
#   ##   all.t.two.sample.test(x = x, y = y, delta0 = delta0,alpha = alpha)
},rownames = TRUE)

output$loc <- renderTable({
    delta0 <- as.numeric(input$delta0)
    alpha <- as.numeric(input$alpha)
    df <- d()
    
    x <- df[,input$variable1]
    y <- df[,input$variable2]
   all.wilcoxon.two.sample.test(x = x, y = y, delta0 = delta0,alpha = alpha)},rownames = TRUE)

output$variance <- renderTable({
    sigma0 <- as.numeric(input$sigma0)
    alpha <- as.numeric(input$alpha)
    df <- d()
    
    x <- df[,input$variable1]
    y <- df[,input$variable2]
   all.var.two.sample.test(x = x, y = y, ratio = sigma0,alpha = alpha)},rownames = TRUE)

output$ansari <- renderTable({
    sigma0 <- as.numeric(input$sigma0)
    alpha <- as.numeric(input$alpha)
    df <- d()
    
    x <- df[,input$variable1]
    y <- df[,input$variable2]
   all.ansari.two.sample.test(x = x, y = y, alpha = alpha)},rownames = TRUE)


  output$tableUImean <- renderUI({
    delta0 <- as.numeric(input$delta0)
    alpha <- as.numeric(input$alpha)
    tagList(
      withMathJax(),
      withMathJax(tableOutput("mean"))
    )
  })
    output$tableUIloc <- renderUI({
    delta0 <- as.numeric(input$delta0)
    alpha <- as.numeric(input$alpha)
    tagList(
      withMathJax(),
      withMathJax(tableOutput("loc"))
    )
  })
      output$tableUIvar <- renderUI({
    delta0 <- as.numeric(input$delta0)
    alpha <- as.numeric(input$alpha)
    tagList(
      withMathJax(),
      withMathJax(tableOutput("variance"))
    )
  })
  output$tableUIansari <- renderUI({
    delta0 <- as.numeric(input$delta0)
    alpha <- as.numeric(input$alpha)
    tagList(
      withMathJax(),
      withMathJax(tableOutput("ansari"))
    )
  })
```


If you have any question or want to report to *israel.almodovar@upr.edu* or *maitra@iastate.edu*. To learn more, see [FIRSTkit](https://github.com/ialmodovar/FIRSTkit).
